/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package comicchecker;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
//    @Test public void testSomeLibraryMethod() {
//        Library classUnderTest = new Library();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//    }
//    
//    @Test
//    public void test1(){
//    	Library a = new Library();
//    	assertEquals(true, a.someLibraryMethod());
//    }
}
